CREATE TABLE "AUTONOMOUS_DW_LANDING_OWNER"."DWH_TECHNOLOGY_TYPE" 
   (	"TECHNOLOGY_TYPE_CODE" NUMBER(38,0), 
	"NAME" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP", 
	"RATING" NUMBER(5,2), 
	"DESCRIPTION" VARCHAR2(300 CHAR) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP", 
	"SOURCE_SYSTEM" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP", 
	"SYNC_STATUS" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP", 
	"SYNC_VERSION" NUMBER(38,0), 
	"LAST_SYNCED_AT" TIMESTAMP (6), 
	"DELETED_FLAG" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

GRANT SELECT ON autonomous_dw_landing_owner.dwh_technology_type TO autonomous_dw_owner;


