spark.master local[*]
spark.app.name training_service

spark.eventLog.enabled true
spark.eventLog.dir file:/app/logs
spark.history.fs.logDirectory file:/app/logs

spark.ui.enabled true
spark.ui.port 4040

spark.driver.memory 2g
spark.executor.memory 2g
spark.executor.cores 2

spark.pyspark.python python3
spark.pyspark.driver.python python3

spark.driver.extraClassPath /opt/spark/jars/ojdbc11.jar:/opt/spark/jars/postgresql-42.7.3.jar:/opt/spark/jars/oraclepki.jar:/opt/spark/jars/osdt_core.jar:/opt/spark/jars/osdt_cert.jar:/opt/spark/jars/ons.jar:/opt/spark/jars/orai18n.jar:/opt/spark/jars/ucp11.jar:/opt/spark/jars/xdb.jar:/opt/spark/jars/xmlparserv2.jar
spark.executor.extraClassPath /opt/spark/jars/ojdbc11.jar:/opt/spark/jars/postgresql-42.7.3.jar:/opt/spark/jars/oraclepki.jar:/opt/spark/jars/osdt_core.jar:/opt/spark/jars/osdt_cert.jar:/opt/spark/jars/ons.jar:/opt/spark/jars/orai18n.jar:/opt/spark/jars/ucp11.jar:/opt/spark/jars/xdb.jar:/opt/spark/jars/xmlparserv2.jar
spark.serializer org.apache.spark.serializer.KryoSerializer
spark.shuffle.service.enabled true
spark.dynamicAllocation.enabled false

spark.sql.session.timeZone UTC
spark.sql.shuffle.partitions 8