--AUTONOMOUS_DB_OWNER_TBL_APP_EVENTS_STREAM_1_v1.0.0
--"TECHNOLOGY_TYPE TABLE"
SET SERVEROUTPUT ON;
DECLARE
  v_count NUMBER;
  v_text  VARCHAR2(4000);
  v_sql CLOB;
BEGIN
DBMS_OUTPUT.PUT_LINE('[1.] Script running...');

--[1.] CHECK CURRENT USER AND SCHEMA
SELECT COUNT(*) INTO v_count
FROM dual
WHERE sys_context('USERENV', 'SESSION_USER') = 'AUTONOMOUS_DB_OWNER'
AND sys_context('USERENV', 'CON_NAME') = 'G90CE4847B77DFA_TECHHUNTENGINEDB' 
AND sys_context('USERENV', 'DB_NAME') = 'G90CE4847B77DFA_TECHHUNTENGINEDB';
IF v_count = 0 THEN
    RAISE_APPLICATION_ERROR(-20001,'The environment is wrong. Please check the user.');
  END IF;
  DBMS_OUTPUT.PUT_LINE('[2.] The environment is preparing...');
-- Current_User: "AUTONOMOUS_DB_OWNER"	
-- Database_name: "G90CE4847B77DFA_TECHHUNTENGINEDB"	
-- Container_Name: "G90CE4847B77DFA_TECHHUNTENGINEDB"
-- Database_Type: "Pluggable Database (PDB)"

--DELETE TABLE technology_type IF EXIST;
SELECT COUNT(*) INTO v_count
FROM all_tables
WHERE owner = 'AUTONOMOUS_DB_OWNER'
AND table_name = 'APP_EVENTS_STREAM'
AND tablespace_name = 'DATA';
IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE autonomous_db_owner.app_events_stream CASCADE CONSTRAINTS';
END IF;
--CREATE TECHNOLOGY_TYPE TABLE;
v_sql := q'[
        CREATE TABLE autonomous_db_owner.app_events_stream (
          --business columns
          event_id VARCHAR2(100),
          event_timestamp TIMESTAMP,
          event_code VARCHAR2(50),
          event_subcode VARCHAR2(50),
          source_identifier NUMBER,

          --technical columns
          t_dl_source_msg CLOB,
          t_dl_err_status NUMBER,
          t_dl_err_msg VARCHAR2(4000),
          t_dl_topic VARCHAR2(100),
          t_dl_offset NUMBER,
          t_dl_ins_dt TIMESTAMP,
          t_dl_stream_dt VARCHAR2(10)
        )
    ]';
 
EXECUTE IMMEDIATE v_sql;
EXECUTE IMMEDIATE 'GRANT SELECT ON autonomous_db_owner.app_events_stream TO autonomous_db_out_owner';
--[1.] VERIFY IF THE TABLE WAS CREATED RIGHT
SELECT COUNT(*) INTO v_count
FROM all_tables
WHERE owner = 'AUTONOMOUS_DB_OWNER'
AND table_name = 'APP_EVENTS_STREAM'
AND tablespace_name = 'DATA';
IF v_count = 0 THEN
    RAISE_APPLICATION_ERROR(-20001,'The APP_EVENTS_STREAM table wasnt created properly.');
END IF;
DBMS_OUTPUT.PUT_LINE('[2.] The APP_EVENTS_STREAM table was created.');
--CREATE COMMENTS FOR TABLE AND COLUMNS
-- TABLE COMMENT
EXECUTE IMMEDIATE 'COMMENT ON TABLE autonomous_db_owner.app_events_stream IS ''The table contains the json events generated by User Interface Application''';

-- COLUMNS COMMENT
EXECUTE IMMEDIATE 'COMMENT ON COLUMN autonomous_db_owner.app_events_stream.event_id IS ''The id of the generated event''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN autonomous_db_owner.app_events_stream.event_timestamp IS ''The timestamp when the event was generated''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN autonomous_db_owner.app_events_stream.event_code IS ''The event code of the event. (student/company)''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN autonomous_db_owner.app_events_stream.event_subcode IS ''The event subcode of the event (insert/update)''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN autonomous_db_owner.app_events_stream.source_identifier IS ''The id ofthe user who generated the event''';        
      
EXECUTE IMMEDIATE 'COMMENT ON COLUMN autonomous_db_owner.app_events_stream.t_dl_source_msg IS ''The source message of the event''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN autonomous_db_owner.app_events_stream.t_dl_err_status IS ''The error status of the event. (1 - OK/2 - NOK)''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN autonomous_db_owner.app_events_stream.t_dl_err_msg IS ''The error message of the event''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN autonomous_db_owner.app_events_stream.t_dl_topic IS ''The topic of the event (user/company).''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN autonomous_db_owner.app_events_stream.t_dl_offset IS ''The order of generation on the topic''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN autonomous_db_owner.app_events_stream.t_dl_ins_dt IS ''The timestamp when the event was ingested on table''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN autonomous_db_owner.app_events_stream.t_dl_stream_dt IS ''The partition column - The yyyy-mm-dd inserted_date on table''';
     
DBMS_OUTPUT.PUT_LINE('[6.] The script running is done!');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END;
/