\echo '=== START INIT SCRIPT 02_pg_db_tech_owner.sql ==='

-- 1. Create schema if not exists
CREATE SCHEMA IF NOT EXISTS db_tech_owner AUTHORIZATION db_tech_owner;

\echo '==================================';
\echo ' 1. CREATE DATA_SOURCE TABLE      ';
\echo '==================================';

-- 1. Drop table if exists
DROP TABLE IF EXISTS db_tech_owner.data_source CASCADE;

-- 2. Create table
CREATE TABLE db_tech_owner.data_source (
    source_id           BIGINT PRIMARY KEY,
    source_name         VARCHAR(100) NOT NULL,
    source_type         VARCHAR(50) NOT NULL,
    host                VARCHAR(255) NOT NULL,
    port                INTEGER NOT NULL,
    database_name       VARCHAR(100) NOT NULL,
    connection_type     VARCHAR(50) NOT NULL,
    username            VARCHAR(100) NOT NULL,
    password_encrypted  TEXT NOT NULL,
    connection_string   TEXT,
    environment         VARCHAR(50) NOT NULL,

    creation_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by          VARCHAR(50) NOT NULL,
    is_active_flag      VARCHAR(1) NOT NULL CHECK (is_active_flag IN ('Y','N')),
    last_update_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by          VARCHAR(20) NOT NULL
);

ALTER TABLE db_tech_owner.data_source OWNER TO db_tech_owner;

-- 3. Comments
COMMENT ON TABLE db_tech_owner.data_source IS
'Stores configuration for all data sources used by ingestion and processing jobs.';

COMMENT ON COLUMN db_tech_owner.data_source.source_id IS 'Primary key generated by sequence.';
COMMENT ON COLUMN db_tech_owner.data_source.source_name IS 'Name of the data source.';
COMMENT ON COLUMN db_tech_owner.data_source.source_type IS 'Type of source (e.g., POSTGRES, ORACLE, API).';
COMMENT ON COLUMN db_tech_owner.data_source.host IS 'Hostname or IP of the source.';
COMMENT ON COLUMN db_tech_owner.data_source.port IS 'Port of the source.';
COMMENT ON COLUMN db_tech_owner.data_source.database_name IS 'Database/schema name.';
COMMENT ON COLUMN db_tech_owner.data_source.connection_type IS 'Connection type (e.g., JDBC, REST).';
COMMENT ON COLUMN db_tech_owner.data_source.username IS 'Username for connection.';
COMMENT ON COLUMN db_tech_owner.data_source.password_encrypted IS 'Encrypted password.';
COMMENT ON COLUMN db_tech_owner.data_source.connection_string IS 'Full connection string.';
COMMENT ON COLUMN db_tech_owner.data_source.environment IS 'Environment (DEV, TEST, PROD).';
COMMENT ON COLUMN db_tech_owner.data_source.creation_date IS 'Technical column - creation timestamp.';
COMMENT ON COLUMN db_tech_owner.data_source.created_by IS 'Technical column - creator user.';
COMMENT ON COLUMN db_tech_owner.data_source.is_active_flag IS 'Indicates if the source is active (Y/N).';
COMMENT ON COLUMN db_tech_owner.data_source.last_update_date IS 'Technical column - last update timestamp.';
COMMENT ON COLUMN db_tech_owner.data_source.updated_by IS 'Technical column - last update user.';

-- 4. Drop sequence if exists
DROP SEQUENCE IF EXISTS db_tech_owner.seq_data_source_pk;

-- 5. Create sequence
CREATE SEQUENCE db_tech_owner.seq_data_source_pk
    START WITH 1
    INCREMENT BY 1
    NO CYCLE;

-- 6. Drop trigger for PK if exists
DROP TRIGGER IF EXISTS trg_data_source_pk ON db_tech_owner.data_source;

-- 7. Create trigger function for PK
CREATE OR REPLACE FUNCTION db_tech_owner.fn_data_source_pk()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.source_id IS NULL THEN
        NEW.source_id := nextval('db_tech_owner.seq_data_source_pk');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 8. Create trigger for PK
CREATE TRIGGER trg_data_source_pk
BEFORE INSERT ON db_tech_owner.data_source
FOR EACH ROW EXECUTE FUNCTION db_tech_owner.fn_data_source_pk();

-- 9. Drop trigger for technical columns if exists
DROP TRIGGER IF EXISTS trg_data_source_tech_col ON db_tech_owner.data_source;

-- 10. Create trigger function for technical columns
CREATE OR REPLACE FUNCTION db_tech_owner.fn_data_source_tech_col()
RETURNS TRIGGER AS $$
BEGIN
    NEW.created_by := CURRENT_USER;
    NEW.creation_date := CURRENT_TIMESTAMP;
    NEW.last_update_date := CURRENT_TIMESTAMP;
    NEW.updated_by := CURRENT_USER;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 11. Create trigger for technical columns
CREATE TRIGGER trg_data_source_tech_col
BEFORE INSERT ON db_tech_owner.data_source
FOR EACH ROW EXECUTE FUNCTION db_tech_owner.fn_data_source_tech_col();

\echo '==================================';
\echo ' 2. CREATE GROUP_TABLE            ';
\echo '==================================';

-- 1. Drop table if exists
DROP TABLE IF EXISTS db_tech_owner.group_table CASCADE;

-- 2. Create table
CREATE TABLE db_tech_owner.group_table (
    group_id           BIGINT PRIMARY KEY,
    group_name         VARCHAR(200) NOT NULL,
    group_description  VARCHAR(200) NOT NULL,
    creation_date      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by         VARCHAR(50) NOT NULL,
    is_active_flag     VARCHAR(1) NOT NULL CHECK (is_active_flag IN ('Y','N')),
    last_update_date   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by         VARCHAR(20) NOT NULL
);

ALTER TABLE db_tech_owner.group_table OWNER TO db_tech_owner;

-- 3. Comments
COMMENT ON TABLE db_tech_owner.group_table IS
'Defines logical groups of ingestion or processing jobs.';

COMMENT ON COLUMN db_tech_owner.group_table.group_id IS 'Primary key generated by sequence.';
COMMENT ON COLUMN db_tech_owner.group_table.group_name IS 'Name of the group.';
COMMENT ON COLUMN db_tech_owner.group_table.group_description IS 'Description of the group.';
COMMENT ON COLUMN db_tech_owner.group_table.creation_date IS 'Technical column - creation timestamp.';
COMMENT ON COLUMN db_tech_owner.group_table.created_by IS 'Technical column - creator user.';
COMMENT ON COLUMN db_tech_owner.group_table.is_active_flag IS 'Indicates if the group is active (Y/N).';
COMMENT ON COLUMN db_tech_owner.group_table.last_update_date IS 'Technical column - last update timestamp.';
COMMENT ON COLUMN db_tech_owner.group_table.updated_by IS 'Technical column - last update user.';

-- 4. Drop sequence if exists
DROP SEQUENCE IF EXISTS db_tech_owner.seq_group_table_pk;

-- 5. Create sequence
CREATE SEQUENCE db_tech_owner.seq_group_table_pk
    START WITH 1
    INCREMENT BY 1
    NO CYCLE;

-- 6. Drop trigger for PK if exists
DROP TRIGGER IF EXISTS trg_group_table_pk ON db_tech_owner.group_table;

-- 7. Create trigger function for PK
CREATE OR REPLACE FUNCTION db_tech_owner.fn_group_table_pk()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.group_id IS NULL THEN
        NEW.group_id := nextval('db_tech_owner.seq_group_table_pk');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 8. Create trigger for PK
CREATE TRIGGER trg_group_table_pk
BEFORE INSERT ON db_tech_owner.group_table
FOR EACH ROW EXECUTE FUNCTION db_tech_owner.fn_group_table_pk();

-- 9. Drop trigger for technical columns if exists
DROP TRIGGER IF EXISTS trg_group_table_tech_col ON db_tech_owner.group_table;

-- 10. Create trigger function for technical columns
CREATE OR REPLACE FUNCTION db_tech_owner.fn_group_table_tech_col()
RETURNS TRIGGER AS $$
BEGIN
    NEW.created_by := CURRENT_USER;
    NEW.creation_date := CURRENT_TIMESTAMP;
    NEW.last_update_date := CURRENT_TIMESTAMP;
    NEW.updated_by := CURRENT_USER;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 11. Create trigger for technical columns
CREATE TRIGGER trg_group_table_tech_col
BEFORE INSERT ON db_tech_owner.group_table
FOR EACH ROW EXECUTE FUNCTION db_tech_owner.fn_group_table_tech_col();



\echo '==================================';
\echo ' 3. CREATE SOURCE_TABLE           ';
\echo '==================================';

-- 1. Drop table if exists
DROP TABLE IF EXISTS db_tech_owner.source_table CASCADE;

-- 2. Create table
CREATE TABLE db_tech_owner.source_table (
    table_id           BIGINT PRIMARY KEY,
    source_id          BIGINT NOT NULL REFERENCES db_tech_owner.data_source(source_id),
    table_name         VARCHAR(200) NOT NULL,
    table_type         VARCHAR(50) NOT NULL,
    table_description  VARCHAR(200) NOT NULL,
    group_id           BIGINT REFERENCES db_tech_owner.group_table(group_id),

    creation_date      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by         VARCHAR(50) NOT NULL,
    is_active_flag     VARCHAR(1) NOT NULL CHECK (is_active_flag IN ('Y','N')),
    last_update_date   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by         VARCHAR(20) NOT NULL
);

ALTER TABLE db_tech_owner.source_table OWNER TO db_tech_owner;

-- 3. Comments
COMMENT ON TABLE db_tech_owner.source_table IS
'Stores metadata about source tables belonging to a data source.';

COMMENT ON COLUMN db_tech_owner.source_table.table_id IS 'Primary key generated by sequence.';
COMMENT ON COLUMN db_tech_owner.source_table.source_id IS 'Foreign key to data_source.';
COMMENT ON COLUMN db_tech_owner.source_table.table_name IS 'Name of the table in the source system.';
COMMENT ON COLUMN db_tech_owner.source_table.table_type IS 'Type of table (BASE, VIEW, etc.).';
COMMENT ON COLUMN db_tech_owner.source_table.table_description IS 'Description of the table.';
COMMENT ON COLUMN db_tech_owner.source_table.group_id IS 'Foreign key to group_table.';
COMMENT ON COLUMN db_tech_owner.source_table.creation_date IS 'Technical column - creation timestamp.';
COMMENT ON COLUMN db_tech_owner.source_table.created_by IS 'Technical column - creator user.';
COMMENT ON COLUMN db_tech_owner.source_table.is_active_flag IS 'Indicates if the table is active (Y/N).';
COMMENT ON COLUMN db_tech_owner.source_table.last_update_date IS 'Technical column - last update timestamp.';
COMMENT ON COLUMN db_tech_owner.source_table.updated_by IS 'Technical column - last update user.';

-- 4. Drop sequence if exists
DROP SEQUENCE IF EXISTS db_tech_owner.seq_source_table_pk;

-- 5. Create sequence
CREATE SEQUENCE db_tech_owner.seq_source_table_pk
    START WITH 1
    INCREMENT BY 1
    NO CYCLE;

-- 6. Drop trigger for PK if exists
DROP TRIGGER IF EXISTS trg_source_table_pk ON db_tech_owner.source_table;

-- 7. Create trigger function for PK
CREATE OR REPLACE FUNCTION db_tech_owner.fn_source_table_pk()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.table_id IS NULL THEN
        NEW.table_id := nextval('db_tech_owner.seq_source_table_pk');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 8. Create trigger for PK
CREATE TRIGGER trg_source_table_pk
BEFORE INSERT ON db_tech_owner.source_table
FOR EACH ROW EXECUTE FUNCTION db_tech_owner.fn_source_table_pk();

-- 9. Drop trigger for technical columns if exists
DROP TRIGGER IF EXISTS trg_source_table_tech_col ON db_tech_owner.source_table;

-- 10. Create trigger function for technical columns
CREATE OR REPLACE FUNCTION db_tech_owner.fn_source_table_tech_col()
RETURNS TRIGGER AS $$
BEGIN
    NEW.created_by := CURRENT_USER;
    NEW.creation_date := CURRENT_TIMESTAMP;
    NEW.last_update_date := CURRENT_TIMESTAMP;
    NEW.updated_by := CURRENT_USER;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 11. Create trigger for technical columns
CREATE TRIGGER trg_source_table_tech_col
BEFORE INSERT ON db_tech_owner.source_table
FOR EACH ROW EXECUTE FUNCTION db_tech_owner.fn_source_table_tech_col();


\echo '==================================';
\echo ' 4. CREATE INGESTION_JOB TABLE    ';
\echo '==================================';

-- 1. Drop table if exists
DROP TABLE IF EXISTS db_tech_owner.ingestion_job CASCADE;

-- 2. Create table
CREATE TABLE db_tech_owner.ingestion_job (
    job_id                BIGINT PRIMARY KEY,
    job_name              VARCHAR(200) NOT NULL,
    job_description       VARCHAR(500) NOT NULL,

    source_id             BIGINT NOT NULL 
                          REFERENCES db_tech_owner.data_source(source_id),

    target_id             BIGINT NOT NULL 
                          REFERENCES db_tech_owner.data_source(source_id),

    job_type              VARCHAR(50) NOT NULL,
    truncate_before_load  VARCHAR(1) NOT NULL CHECK (truncate_before_load IN ('Y','N')),
    incremental_column    VARCHAR(200),
    airbyte_connection_id VARCHAR(100),

    creation_date         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by            VARCHAR(50) NOT NULL,
    is_active_flag        VARCHAR(1) NOT NULL CHECK (is_active_flag IN ('Y','N')),
    last_update_date      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by            VARCHAR(20) NOT NULL
);

ALTER TABLE db_tech_owner.ingestion_job OWNER TO db_tech_owner;

-- 3. Comments
COMMENT ON TABLE db_tech_owner.ingestion_job IS
'Defines ingestion jobs used by Airbyte, Spark or custom pipelines.';

COMMENT ON COLUMN db_tech_owner.ingestion_job.job_id IS 'Primary key generated by sequence.';
COMMENT ON COLUMN db_tech_owner.ingestion_job.job_name IS 'Name of the ingestion job.';
COMMENT ON COLUMN db_tech_owner.ingestion_job.job_description IS 'Description of the job.';
COMMENT ON COLUMN db_tech_owner.ingestion_job.source_id IS 'Foreign key to source data source.';
COMMENT ON COLUMN db_tech_owner.ingestion_job.target_id IS 'Foreign key to target data source.';
COMMENT ON COLUMN db_tech_owner.ingestion_job.job_type IS 'Type of job (FULL, INCREMENTAL, CDC, etc.).';
COMMENT ON COLUMN db_tech_owner.ingestion_job.truncate_before_load IS 'Indicates if target table should be truncated before load.';
COMMENT ON COLUMN db_tech_owner.ingestion_job.incremental_column IS 'Column used for incremental logic.';
COMMENT ON COLUMN db_tech_owner.ingestion_job.airbyte_connection_id IS 'Airbyte connection ID.';
COMMENT ON COLUMN db_tech_owner.ingestion_job.creation_date IS 'Technical column - creation timestamp.';
COMMENT ON COLUMN db_tech_owner.ingestion_job.created_by IS 'Technical column - creator user.';
COMMENT ON COLUMN db_tech_owner.ingestion_job.is_active_flag IS 'Indicates if the job is active (Y/N).';
COMMENT ON COLUMN db_tech_owner.ingestion_job.last_update_date IS 'Technical column - last update timestamp.';
COMMENT ON COLUMN db_tech_owner.ingestion_job.updated_by IS 'Technical column - last update user.';

-- 4. Drop sequence if exists
DROP SEQUENCE IF EXISTS db_tech_owner.seq_ingestion_job_pk;

-- 5. Create sequence
CREATE SEQUENCE db_tech_owner.seq_ingestion_job_pk
    START WITH 1
    INCREMENT BY 1
    NO CYCLE;

-- 6. Drop trigger for PK if exists
DROP TRIGGER IF EXISTS trg_ingestion_job_pk ON db_tech_owner.ingestion_job;

-- 7. Create trigger function for PK
CREATE OR REPLACE FUNCTION db_tech_owner.fn_ingestion_job_pk()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.job_id IS NULL THEN
        NEW.job_id := nextval('db_tech_owner.seq_ingestion_job_pk');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 8. Create trigger for PK
CREATE TRIGGER trg_ingestion_job_pk
BEFORE INSERT ON db_tech_owner.ingestion_job
FOR EACH ROW EXECUTE FUNCTION db_tech_owner.fn_ingestion_job_pk();

-- 9. Drop trigger for technical columns if exists
DROP TRIGGER IF EXISTS trg_ingestion_job_tech_col ON db_tech_owner.ingestion_job;

-- 10. Create trigger function for technical columns
CREATE OR REPLACE FUNCTION db_tech_owner.fn_ingestion_job_tech_col()
RETURNS TRIGGER AS $$
BEGIN
    NEW.created_by := CURRENT_USER;
    NEW.creation_date := CURRENT_TIMESTAMP;
    NEW.last_update_date := CURRENT_TIMESTAMP;
    NEW.updated_by := CURRENT_USER;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 11. Create trigger for technical columns
CREATE TRIGGER trg_ingestion_job_tech_col
BEFORE INSERT ON db_tech_owner.ingestion_job
FOR EACH ROW EXECUTE FUNCTION db_tech_owner.fn_ingestion_job_tech_col();

\echo '==================================';
\echo ' 5. CREATE GROUP_JOBS TABLE       ';
\echo '==================================';

-- 1. Drop table if exists
DROP TABLE IF EXISTS db_tech_owner.group_jobs CASCADE;

-- 2. Create table
CREATE TABLE db_tech_owner.group_jobs (
    group_id          BIGINT NOT NULL 
                      REFERENCES db_tech_owner.group_table(group_id),

    job_id            BIGINT NOT NULL 
                      REFERENCES db_tech_owner.ingestion_job(job_id),

    run_order         INTEGER NOT NULL,
    execution_mode    VARCHAR(20) NOT NULL,

    creation_date     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by        VARCHAR(50) NOT NULL,
    is_active_flag    VARCHAR(1) NOT NULL CHECK (is_active_flag IN ('Y','N')),
    last_update_date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by        VARCHAR(20) NOT NULL,

    PRIMARY KEY (group_id, job_id)
);

ALTER TABLE db_tech_owner.group_jobs OWNER TO db_tech_owner;

-- 3. Comments
COMMENT ON TABLE db_tech_owner.group_jobs IS
'Associates ingestion jobs with groups and defines execution order and mode.';

COMMENT ON COLUMN db_tech_owner.group_jobs.group_id IS 'Foreign key to group_table.';
COMMENT ON COLUMN db_tech_owner.group_jobs.job_id IS 'Foreign key to ingestion_job.';
COMMENT ON COLUMN db_tech_owner.group_jobs.run_order IS 'Execution order inside the group.';
COMMENT ON COLUMN db_tech_owner.group_jobs.execution_mode IS 'Execution mode (SEQUENTIAL, PARALLEL).';
COMMENT ON COLUMN db_tech_owner.group_jobs.creation_date IS 'Technical column - creation timestamp.';
COMMENT ON COLUMN db_tech_owner.group_jobs.created_by IS 'Technical column - creator user.';
COMMENT ON COLUMN db_tech_owner.group_jobs.is_active_flag IS 'Indicates if the mapping is active (Y/N).';
COMMENT ON COLUMN db_tech_owner.group_jobs.last_update_date IS 'Technical column - last update timestamp.';
COMMENT ON COLUMN db_tech_owner.group_jobs.updated_by IS 'Technical column - last update user.';

-- 4. Drop trigger for technical columns if exists
DROP TRIGGER IF EXISTS trg_group_jobs_tech_col ON db_tech_owner.group_jobs;

-- 5. Create trigger function for technical columns
CREATE OR REPLACE FUNCTION db_tech_owner.fn_group_jobs_tech_col()
RETURNS TRIGGER AS $$
BEGIN
    NEW.created_by := CURRENT_USER;
    NEW.creation_date := CURRENT_TIMESTAMP;
    NEW.last_update_date := CURRENT_TIMESTAMP;
    NEW.updated_by := CURRENT_USER;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 6. Create trigger for technical columns
CREATE TRIGGER trg_group_jobs_tech_col
BEFORE INSERT ON db_tech_owner.group_jobs
FOR EACH ROW EXECUTE FUNCTION db_tech_owner.fn_group_jobs_tech_col();

\echo '==========================================';
\echo ' 6. CREATE PROCESSES_METADATA TABLE       ';
\echo '==========================================';

-- 1. Drop table if exists
DROP TABLE IF EXISTS db_tech_owner.processes_metadata CASCADE;

-- 2. Create table
CREATE TABLE db_tech_owner.processes_metadata (
    process_code       BIGINT PRIMARY KEY,
    process_name       VARCHAR(200) NOT NULL,
    process_type       VARCHAR(30) NOT NULL,
    group_id           BIGINT REFERENCES db_tech_owner.group_table(group_id),
    run_order          INTEGER NOT NULL,
    execution_mode     VARCHAR(20) NOT NULL,
    frequency          VARCHAR(50),
    start_condition    VARCHAR(4000),
    expected_rows      INTEGER,
    waiting_time       INTEGER,
    retry_time         INTEGER,

    creation_date      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by         VARCHAR(50) NOT NULL,
    last_update_date   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_updated_by    VARCHAR(50) NOT NULL,
    source_system      VARCHAR(20) NOT NULL CHECK (source_system IN ('db_env','dw_env','pg_env'))
);

ALTER TABLE db_tech_owner.processes_metadata OWNER TO db_tech_owner;

-- 3. Comments
COMMENT ON TABLE db_tech_owner.processes_metadata IS
'Metadata for all orchestrated processes (Airflow DAGs, Spark jobs, cleanup jobs, etc.).';

COMMENT ON COLUMN db_tech_owner.processes_metadata.process_code IS 'Primary key generated by sequence.';
COMMENT ON COLUMN db_tech_owner.processes_metadata.process_name IS 'Name of the process.';
COMMENT ON COLUMN db_tech_owner.processes_metadata.process_type IS 'Type of the process.';
COMMENT ON COLUMN db_tech_owner.processes_metadata.group_id IS 'Foreign key to group_table.';
COMMENT ON COLUMN db_tech_owner.processes_metadata.run_order IS 'Execution order inside the group.';
COMMENT ON COLUMN db_tech_owner.processes_metadata.execution_mode IS 'Execution mode (e.g., SEQUENTIAL, PARALLEL).';
COMMENT ON COLUMN db_tech_owner.processes_metadata.frequency IS 'Execution frequency.';
COMMENT ON COLUMN db_tech_owner.processes_metadata.start_condition IS 'Start condition logic.';
COMMENT ON COLUMN db_tech_owner.processes_metadata.expected_rows IS 'Expected number of rows.';
COMMENT ON COLUMN db_tech_owner.processes_metadata.waiting_time IS 'Waiting time before execution.';
COMMENT ON COLUMN db_tech_owner.processes_metadata.retry_time IS 'Retry time in case of failure.';
COMMENT ON COLUMN db_tech_owner.processes_metadata.creation_date IS 'Technical column - creation timestamp.';
COMMENT ON COLUMN db_tech_owner.processes_metadata.created_by IS 'Technical column - creator user.';
COMMENT ON COLUMN db_tech_owner.processes_metadata.last_update_date IS 'Technical column - last update timestamp.';
COMMENT ON COLUMN db_tech_owner.processes_metadata.last_updated_by IS 'Technical column - last update user.';
COMMENT ON COLUMN db_tech_owner.processes_metadata.source_system IS 'Technical column - source system.';

-- 4. Drop sequence if exists
DROP SEQUENCE IF EXISTS db_tech_owner.seq_processes_metadata_pk;

-- 5. Create sequence
CREATE SEQUENCE db_tech_owner.seq_processes_metadata_pk
    START WITH 1
    INCREMENT BY 1
    NO CYCLE;

-- 6. Drop trigger for PK if exists
DROP TRIGGER IF EXISTS trg_processes_metadata_pk ON db_tech_owner.processes_metadata;

-- 7. Create trigger function for PK
CREATE OR REPLACE FUNCTION db_tech_owner.fn_processes_metadata_pk()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.process_code IS NULL THEN
        NEW.process_code := nextval('db_tech_owner.seq_processes_metadata_pk');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 8. Create trigger for PK
CREATE TRIGGER trg_processes_metadata_pk
BEFORE INSERT ON db_tech_owner.processes_metadata
FOR EACH ROW EXECUTE FUNCTION db_tech_owner.fn_processes_metadata_pk();

-- 9. Drop trigger for technical columns if exists
DROP TRIGGER IF EXISTS trg_processes_metadata_tech_col ON db_tech_owner.processes_metadata;

-- 10. Create trigger function for technical columns
CREATE OR REPLACE FUNCTION db_tech_owner.fn_processes_metadata_tech_col()
RETURNS TRIGGER AS $$
BEGIN
    NEW.created_by := CURRENT_USER;
    NEW.creation_date := CURRENT_TIMESTAMP;
    NEW.last_update_date := CURRENT_TIMESTAMP;
    NEW.last_updated_by := CURRENT_USER;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 11. Create trigger for technical columns
CREATE TRIGGER trg_processes_metadata_tech_col
BEFORE INSERT ON db_tech_owner.processes_metadata
FOR EACH ROW EXECUTE FUNCTION db_tech_owner.fn_processes_metadata_tech_col();


\echo '==================================';
\echo ' 7. CREATE PROCESSES_NOTIF TABLE  ';
\echo '==================================';

-- 1. Drop table if exists
DROP TABLE IF EXISTS db_tech_owner.processes_notif CASCADE;

-- 2. Create table
CREATE TABLE db_tech_owner.processes_notif (
    notification_id      BIGINT PRIMARY KEY,
    process_name         VARCHAR(100) NOT NULL,
    process_date         VARCHAR(10) NOT NULL,
    process_type         VARCHAR(30) NOT NULL,
    start_timestamp      TIMESTAMP NOT NULL,
    end_timestamp        TIMESTAMP NOT NULL,
    status               VARCHAR(30) NOT NULL CHECK (status IN ('IN_PROGRESS','ERROR','DONE')),
    error_message        VARCHAR(4000),
    admin_user           VARCHAR(50) NOT NULL,

    creation_date        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by           VARCHAR(50) NOT NULL,
    source_system        VARCHAR(20) NOT NULL CHECK (source_system IN ('db_env','dw_env','pg_env')),
    target_system        VARCHAR(20) NOT NULL CHECK (target_system IN ('db_env','dw_env','pg_env'))
);

ALTER TABLE db_tech_owner.processes_notif OWNER TO db_tech_owner;

-- 3. Comments
COMMENT ON TABLE db_tech_owner.processes_notif IS
'Stores notifications and execution logs for all processes.';

COMMENT ON COLUMN db_tech_owner.processes_notif.notification_id IS 'Primary key generated by sequence.';
COMMENT ON COLUMN db_tech_owner.processes_notif.process_name IS 'Name of the process.';
COMMENT ON COLUMN db_tech_owner.processes_notif.process_date IS 'Execution date (YYYY-MM-DD).';
COMMENT ON COLUMN db_tech_owner.processes_notif.process_type IS 'Type of the process.';
COMMENT ON COLUMN db_tech_owner.processes_notif.start_timestamp IS 'Start timestamp.';
COMMENT ON COLUMN db_tech_owner.processes_notif.end_timestamp IS 'End timestamp.';
COMMENT ON COLUMN db_tech_owner.processes_notif.status IS 'Execution status.';
COMMENT ON COLUMN db_tech_owner.processes_notif.error_message IS 'Error message if failed.';
COMMENT ON COLUMN db_tech_owner.processes_notif.admin_user IS 'User who triggered the process.';
COMMENT ON COLUMN db_tech_owner.processes_notif.creation_date IS 'Technical column - creation timestamp.';
COMMENT ON COLUMN db_tech_owner.processes_notif.created_by IS 'Technical column - creator user.';
COMMENT ON COLUMN db_tech_owner.processes_notif.source_system IS 'Technical column - source system.';

-- 4. Drop sequence if exists
DROP SEQUENCE IF EXISTS db_tech_owner.seq_processes_notif_pk;

-- 5. Create sequence
CREATE SEQUENCE db_tech_owner.seq_processes_notif_pk
    START WITH 1
    INCREMENT BY 1
    NO CYCLE;

-- 6. Drop trigger for PK if exists
DROP TRIGGER IF EXISTS trg_processes_notif_pk ON db_tech_owner.processes_notif;

-- 7. Create trigger function for PK
CREATE OR REPLACE FUNCTION db_tech_owner.fn_processes_notif_pk()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.notification_id IS NULL THEN
        NEW.notification_id := nextval('db_tech_owner.seq_processes_notif_pk');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 8. Create trigger for PK
CREATE TRIGGER trg_processes_notif_pk
BEFORE INSERT ON db_tech_owner.processes_notif
FOR EACH ROW EXECUTE FUNCTION db_tech_owner.fn_processes_notif_pk();

-- 9. Drop trigger for technical columns if exists
DROP TRIGGER IF EXISTS trg_processes_notif_tech_col ON db_tech_owner.processes_notif;

-- 10. Create trigger function for technical columns
CREATE OR REPLACE FUNCTION db_tech_owner.fn_processes_notif_tech_col()
RETURNS TRIGGER AS $$
BEGIN
    NEW.created_by := CURRENT_USER;
    NEW.creation_date := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 11. Create trigger for technical columns
CREATE TRIGGER trg_processes_notif_tech_col
BEFORE INSERT ON db_tech_owner.processes_notif
FOR EACH ROW EXECUTE FUNCTION db_tech_owner.fn_processes_notif_tech_col();

\echo '==============================================================';
\echo ' 8. CREATE CLEANUP FUNCTION FOR PROCESSES_NOTIF TABLE         ';
\echo '==============================================================';

CREATE OR REPLACE FUNCTION db_tech_owner.fn_cleanup_processes_notif()
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    v_start_ts TIMESTAMP := NOW();
    v_end_ts   TIMESTAMP;
    v_deleted  INTEGER := 0;
    v_exists   INTEGER := 0;
    v_error    TEXT;
BEGIN
    -- Check if there are rows older than 1 month
    SELECT COUNT(*) INTO v_exists
    FROM db_tech_owner.processes_notif
    WHERE creation_date < NOW() - INTERVAL '1 month';

    IF v_exists = 0 THEN
        RETURN;
    END IF;

    -- Insert IN_PROGRESS log
    INSERT INTO db_tech_owner.processes_notif (
        process_name, process_date, process_type,
        start_timestamp, status, admin_user
    ) VALUES (
        'PROCESSES_NOTIF_CLEAN_UP_PROCESS',
        TO_CHAR(NOW(), 'YYYY-MM-DD'),
        'CLEAN_UP',
        v_start_ts,
        'IN_PROGRESS',
        'POSTGRES_SYSTEM'
    );

    -- Cleanup logic
    DELETE FROM db_tech_owner.processes_notif
    WHERE creation_date < NOW() - INTERVAL '1 month';

    v_deleted := SQL%ROWCOUNT;
    v_end_ts := NOW();

    -- Insert DONE log
    INSERT INTO db_tech_owner.processes_notif (
        process_name, process_date, process_type,
        start_timestamp, end_timestamp, status,
        error_message, admin_user
    ) VALUES (
        'PROCESSES_NOTIF_CLEAN_UP_PROCESS',
        TO_CHAR(NOW(), 'YYYY-MM-DD'),
        'CLEAN_UP',
        v_start_ts,
        v_end_ts,
        'DONE',
        'Deleted ' || v_deleted || ' rows older than 1 month',
        'POSTGRES_SYSTEM'
    );

EXCEPTION WHEN OTHERS THEN
    v_end_ts := NOW();
    v_error := SQLERRM;

    INSERT INTO db_tech_owner.processes_notif (
        process_name, process_date, process_type,
        start_timestamp, end_timestamp, status,
        error_message, admin_user
    ) VALUES (
        'PROCESSES_NOTIF_CLEAN_UP_PROCESS',
        TO_CHAR(NOW(), 'YYYY-MM-DD'),
        'CLEAN_UP',
        v_start_ts,
        v_end_ts,
        'ERROR',
        v_error,
        'POSTGRES_SYSTEM'
    );
END;
$$;

\echo '=== END INIT SCRIPT 02_pg_db_tech_owner.sql ==='